name: main
on: [push]

jobs:
  pages-directory-listing:
    runs-on: ubuntu-latest
    name: Run Actions Template
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            data

      - name: Github Pages Directory Listing
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: data

      - name: Debug - List files in data directory
        run: ls -al data

      - name: Upload artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'data'
          name: 'github-pages'

  deploy:
    needs: pages-directory-listing
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug - List uploaded artifacts
        run: echo "Artifacts: ${{ steps.upload.outputs.artifact-name }}"

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        with:
          artifact_name: 'github-pages'
          
          
# name: main
# on: [push]

# jobs:
#   pages-directory-listing:
#     runs-on: ubuntu-latest
#     name: Run Actions Template
#     steps:
#       # To use this repository's private action,
#       # you must check out the repository
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           sparse-checkout: |
#             data

#       - name: Github Pages Directory Listing
#         uses: jayanta525/github-pages-directory-listing@v4.0.0
#         with:
#           FOLDER: data

#       - name: Upload artifact
#         uses: actions/upload-pages-artifact@v3
#         with:
#           # Upload generator folder
#           path: 'data'

#   deploy:
#     needs: pages-directory-listing
#     permissions:
#       pages: write      # to deploy to Pages
#       id-token: write   # to verify the deployment originates from an appropriate source

#     # Deploy to the github-pages environment
#     environment:
#       name: github-pages
#       # url: ${{ steps.upload-artifact.outputs.artifact-url }}

#     # Specify runner + deployment step
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy to GitHub Pages
#         id: deployment
#         uses: actions/deploy-pages@v1
